[project]
name = "debatebet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.62.0",
    "pydantic-settings>=2.7.1",
]
